apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'oci://registry-1.docker.io/bitnamicharts'
    chart: redis
    targetRevision: 24.0.8
    helm:
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://github.com/port-gh-app-dev/sample-value-file.git'
    targetRevision: main
    ref: values
    path: .
operation:
  initiatedBy:
    username: admin
  sync:
    syncStrategy:
      hook: {}
